name: Checks

on: [ push, pull_request ]

# For a more complex build matrix example see:
# https://github.com/evandroforks/anki/blob/master/.github/workflows/checks.yml
jobs:

  test:
    name: Tests on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ ubuntu-latest ]

      # Keep all systems running if something fails
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure OS environment variables
        id: environment_variables
        run: |
          set -x
          RELEASE_TAG="1.1.${{ github.run_number }}-$(git rev-parse --short HEAD)"
          PREFIX_NAME="ufscthesisx-light"
          RELEASE_FILE="${PREFIX_NAME}.zip"
          RELEASE_NAME="${RELEASE_TAG}.zip"

          echo "::set-output name=RELEASE_TAG::${RELEASE_TAG}"
          echo "::set-output name=PREFIX_NAME::${PREFIX_NAME}"
          echo "::set-output name=RELEASE_FILE::${RELEASE_FILE}"
          echo "::set-output name=RELEASE_NAME::${RELEASE_NAME}"

          if curl --head --fail --show-error https://github.com/${GITHUB_REPOSITORY}/releases/${RELEASE_TAG};
          then :
            echo "::set-output name=RELEASE_FILE_EXISTS::true";
          else
            echo "::set-output name=RELEASE_FILE_EXISTS::false";
          fi

      - name: Create .zip Release
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            set -x
            apk add make unzip zip python3

            make release version="${{ steps.environment_variables.outputs.RELEASE_NAME }}" version_prefix="${{ steps.environment_variables.outputs.PREFIX_NAME }}"
            unzip "${{ steps.environment_variables.outputs.RELEASE_NAME }}"

      - name: Create .pdf Release
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            set -x
            apk add make unzip zip python3

            cd "${{ steps.environment_variables.outputs.PREFIX_NAME }}"
            make debug=1 halt=1

      # https://github.com/actions/create-release
      - name: Create GitHub Release
        if: github.ref == 'refs/heads/master' && steps.environment_variables.outputs.RELEASE_FILE_EXISTS == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.environment_variables.outputs.RELEASE_TAG }}
          release_name: Versão ${{ steps.environment_variables.outputs.RELEASE_TAG }}
          body: |
            Contém as alterações mais recentes na ramificação principal deste projeto

            Basta baixar o arquivo `${{ steps.environment_variables.outputs.RELEASE_FILE }}`, descompactar e compilar o arquivo `main.tex`

            [`${{ steps.environment_variables.outputs.RELEASE_FILE }}`](https://github.com/${{ github.repository }}/releases/latest/download/${{ steps.environment_variables.outputs.RELEASE_FILE }}) - `https://github.com/${{ github.repository }}/releases/latest/download/${{ steps.environment_variables.outputs.RELEASE_FILE }}`

            Ou abrir ele diretamente no Overleaf

            [`overleaf upload`](https://overleaf.com/docs?snip_uri=https://github.com/${{ github.repository }}/releases/latest/download/${{ steps.environment_variables.outputs.RELEASE_FILE }}) - `https://overleaf.com/docs?snip_uri=https://github.com/${{ github.repository }}/releases/latest/download/${{ steps.environment_variables.outputs.RELEASE_FILE }}`

          draft: false
          prerelease: false

      # https://github.com/actions/upload-release-asset
      - name: Upload .zip Asset
        if: github.ref == 'refs/heads/master' && steps.environment_variables.outputs.RELEASE_FILE_EXISTS == 'false'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.environment_variables.outputs.RELEASE_NAME }}
          asset_name: ${{ steps.environment_variables.outputs.RELEASE_FILE }}
          asset_content_type: application/zip

      - name: Upload .pdf Asset
        if: github.ref == 'refs/heads/master' && steps.environment_variables.outputs.RELEASE_FILE_EXISTS == 'false'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.environment_variables.outputs.PREFIX_NAME }}/main.pdf
          asset_name: pdf_exemplo.pdf
          asset_content_type: application/pdf
